language: go
sudo: required
go:
  - "1.11"
services:
  - docker

env: GO111MODULE=on

install:
  - go get -u golang.org/x/lint/golint
  - go mod download
  - docker pull ipfs/go-ipfs:v0.4.18

before_script:
  - go vet ./...
  - go build ./...
  - go test -run xxxx ./...
  - make testenv

script:
  - diff -u <(echo -n) <(gofmt -d -s `find . -type f -name '*.go' -not -path "./vendor/*"`)
  - diff -u <(echo -n) <(golint `go list ./... | grep -v /vendor/`)
  - sudo -E env "PATH=$PATH" go test -race -short -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - make release

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Lc7yTvpKm6wjqzGmdSoWxtvAY9U7pWYRI/+0e5iKlAX2jarsq/D9+dUo7K8LfPql3jEqY9P53VNbU0/IB0+J4rrkH0Y4feNu7EqpsP+Jax+OnctKUyzs+AGk6uddxisWHC438U5YNvJKdDmRzCbny+QU7MlAm2KElTuvchzZG13+G/sETK/VaVkmUimM6ao8Ng9QCEkbo/Q9NiEadzN+krJwe6oC/iqUz1uSaDqEiEbsz1neaqxnmgFHcLugknH/YYqMrBxRu86IpZqeMLTloumsmb/MGA/UWUpjxBqSFy8k4D6/RK0Ow1DDzB+7ju6E0o+vGiN6A8EVTPTJg/J2cfjwObu1C1qY8/mX9GbZvOFtYFq7d1Zf0+mK5OiO/3VWuWeF7WZlD3a7g8LbgLXEcrrGOj/Zaaqts9QwDlWcSJDkon46+cZrDd1Ico7Um0+qWmsaHi0oWmU7yAh+Y80nis2Faq3ADilqF8V2ny4owK3cOD3uMJUWHR6LxAAXeBgIhLXFrC3CUrCNcrwyrETK8MSx1R2y2w+T1jQezaFsl4NID+kmbH9En0t0CleWLW1nARYs/yqM9YkRVDgp8xrDeb9bQQUEHMmTxn94qm9KDllJoOKnRFQgdjFU0RovCgiTODqbNQr4Tx/6F7ifdHNPSl8vNG5H7xg5tCxifHuqA7w=
  file_glob: true
  file: release/nexus-*
  on:
    tags: true
    repo: RTradeLtd/Nexus

notifications:
  email: false
