language: go
go:
  - "1.11"
services:
  - docker

env: GO111MODULE=on

install:
  - go get -u golang.org/x/lint/golint
  - go mod download
  - docker pull ipfs/go-ipfs:v0.4.17

before_script:
  - go vet ./...
  - go build ./...
  - go test -run xxxx ./...

script:
  - go fmt ./...
  - golint $(go list ./... | grep -v /vendor/) # golint doesn't ignore vendor
  - go test -race -short -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: 
  email: false 
