language: go
sudo: required
go:
  - "1.11"
services:
  - docker

env: GO111MODULE=on

install:
  - go get -u golang.org/x/lint/golint
  - go mod download
  - docker pull ipfs/go-ipfs:v0.4.19

before_script:
  - go vet ./...
  - go build ./...
  - go test -run xxxx ./...
  - make testenv

script:
  - diff -u <(echo -n) <(gofmt -d -s `find . -type f -name '*.go' -not -path "./vendor/*"`)
  - diff -u <(echo -n) <(golint `go list ./... | grep -v /vendor/`)
  - sudo -E env "PATH=$PATH" go test -race -short -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - make release

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: RqqKNRTMoFyTplqw87QcNRpoXkCdK8sPq0WINhTIi9eZB6QLrx/9hxGoqIBIjHhcNYTYzAyk+izF574NS5n5qlqEvbdxi4Ge3z9bo9eNNS3tUlHxEV4P3tHdynZ8wT6qhs++sgIKjFMJA1cbZp5ZGAEHUnr56ZP5o8LoiDD7z3T65bP4Bj+cq743kfhcekbnCAy5YHPwdJQDWzvvFfkwSb/cKl30fz64nQ3dVj+2H1OURbnNUzejusxvmfygmsEIGRoGAHMJQ+EaUyLD7QZXya2furrLyweJUPNAjr3JZwe5tmpBZjgEwiLvf936OFe089v+40Zm1kap6unsO272w+BTBa/G8X1BBxHJav+r1xYlvB0Aui9+TrvOaA5+Fv/2xkIQaySc82r0BcSlcBA62wjTIDm3PnzTML5DeI22isuvvG6cqcYtX304x0MYgWbSZbkvrDrDJOhGH9ehethc7pcZv9V5VCiq+0mM+xnoGsLxESWIiESLjpdqLrDqaMkdlT+ul14vmq8fSQT1w9eVlNo7vB8XALJhsapqEGiVX6cHsu3aNf+36nDQLCieOlcvc/0rdX5SPovA3mDNMheoObcX0gdxXKiT8u9sFta84yYvQ8CxYrVEOPbr23ytTsl241JR83SC90WWznOTYwR8Q3Ib8Spp4PjGLXGq/D+XoGI=
  file_glob: true
  file: release/nexus-*
  on:
    tags: true
    repo: RTradeLtd/Nexus

notifications:
  email: false
