// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package ipfs_orchestrator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type NetworkRequest struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkRequest) Reset()         { *m = NetworkRequest{} }
func (m *NetworkRequest) String() string { return proto.CompactTextString(m) }
func (*NetworkRequest) ProtoMessage()    {}
func (*NetworkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *NetworkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkRequest.Unmarshal(m, b)
}
func (m *NetworkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkRequest.Marshal(b, m, deterministic)
}
func (m *NetworkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkRequest.Merge(m, src)
}
func (m *NetworkRequest) XXX_Size() int {
	return xxx_messageInfo_NetworkRequest.Size(m)
}
func (m *NetworkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkRequest proto.InternalMessageInfo

func (m *NetworkRequest) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

type StartNetworkResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	SwarmKey             string   `protobuf:"bytes,2,opt,name=swarmKey,proto3" json:"swarmKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartNetworkResponse) Reset()         { *m = StartNetworkResponse{} }
func (m *StartNetworkResponse) String() string { return proto.CompactTextString(m) }
func (*StartNetworkResponse) ProtoMessage()    {}
func (*StartNetworkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *StartNetworkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartNetworkResponse.Unmarshal(m, b)
}
func (m *StartNetworkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartNetworkResponse.Marshal(b, m, deterministic)
}
func (m *StartNetworkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartNetworkResponse.Merge(m, src)
}
func (m *StartNetworkResponse) XXX_Size() int {
	return xxx_messageInfo_StartNetworkResponse.Size(m)
}
func (m *StartNetworkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartNetworkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartNetworkResponse proto.InternalMessageInfo

func (m *StartNetworkResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *StartNetworkResponse) GetSwarmKey() string {
	if m != nil {
		return m.SwarmKey
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "ipfs_orchestrator.Empty")
	proto.RegisterType((*NetworkRequest)(nil), "ipfs_orchestrator.NetworkRequest")
	proto.RegisterType((*StartNetworkResponse)(nil), "ipfs_orchestrator.StartNetworkResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xcc, 0x2c, 0x48, 0x2b, 0x8e,
	0xcf, 0x2f, 0x4a, 0xce, 0x48, 0x2d, 0x2e, 0x29, 0x4a, 0x2c, 0xc9, 0x2f, 0x52, 0x62, 0xe7, 0x62,
	0x75, 0xcd, 0x2d, 0x28, 0xa9, 0x54, 0xd2, 0xe2, 0xe2, 0xf3, 0x4b, 0x2d, 0x29, 0xcf, 0x2f, 0xca,
	0x0e, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0xcf, 0x83, 0x88, 0x48, 0x30,
	0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x4a, 0x2e, 0x5c, 0x22, 0xc1, 0x25, 0x89, 0x45, 0x25,
	0x70, 0x0d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x02, 0x5c, 0xcc, 0x89, 0x05, 0x99, 0x50,
	0xd5, 0x20, 0xa6, 0x90, 0x14, 0x17, 0x47, 0x71, 0x79, 0x62, 0x51, 0xae, 0x77, 0x6a, 0xa5, 0x04,
	0x13, 0x58, 0x18, 0xce, 0x37, 0xfa, 0xcc, 0xc8, 0xc5, 0x1e, 0x0c, 0x71, 0x9f, 0x90, 0x0d, 0x17,
	0x4b, 0x40, 0x66, 0x5e, 0xba, 0x90, 0x84, 0x1e, 0x86, 0x13, 0xf5, 0xc0, 0xee, 0x93, 0xc2, 0x29,
	0xa3, 0xc4, 0x20, 0x14, 0xc3, 0xc5, 0x83, 0xec, 0x1e, 0x21, 0x45, 0x2c, 0x6a, 0x51, 0x3d, 0x27,
	0xa5, 0x8e, 0x45, 0x09, 0x36, 0x3f, 0x29, 0x31, 0x08, 0xf9, 0x70, 0x71, 0x07, 0x97, 0xe4, 0x17,
	0x90, 0x60, 0x38, 0x1e, 0xb7, 0x26, 0xb1, 0x81, 0xa3, 0xc2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0xd7, 0x85, 0x66, 0xdd, 0x9b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	StartNetwork(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*StartNetworkResponse, error)
	StopNetwork(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*Empty, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ipfs_orchestrator.Service/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) StartNetwork(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*StartNetworkResponse, error) {
	out := new(StartNetworkResponse)
	err := c.cc.Invoke(ctx, "/ipfs_orchestrator.Service/StartNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) StopNetwork(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ipfs_orchestrator.Service/StopNetwork", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	Ping(context.Context, *Empty) (*Empty, error)
	StartNetwork(context.Context, *NetworkRequest) (*StartNetworkResponse, error)
	StopNetwork(context.Context, *NetworkRequest) (*Empty, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipfs_orchestrator.Service/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_StartNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).StartNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipfs_orchestrator.Service/StartNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).StartNetwork(ctx, req.(*NetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_StopNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).StopNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ipfs_orchestrator.Service/StopNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).StopNetwork(ctx, req.(*NetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ipfs_orchestrator.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Service_Ping_Handler,
		},
		{
			MethodName: "StartNetwork",
			Handler:    _Service_StartNetwork_Handler,
		},
		{
			MethodName: "StopNetwork",
			Handler:    _Service_StopNetwork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
